name: create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Get latest tag
        id: latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Bump release version
        id: bump_version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.latest_tag.outputs.tag }}
          level: 'minor'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            This is the release created automatically but always minor.
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          token: ${{ secrets.PAT }}