name: create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Get Merged PR Branch
        id: get-branch
        run: |
          # Extract the branch name from the merged pull request
          PR_BRANCH=$(jq -r '.pull_request.head.ref // .github.head_ref' "$GITHUB_EVENT_PATH")
          echo "Merged PR Branch: $PR_BRANCH"
          echo "$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Determine level
        id: determine-level
        run: |
          # Map the branch name to a level
          case "${{ steps.get-branch.outputs.pr_branch }}" in
            patch* | issue* | hotfix* | dependabot/* | whitesource/*)
              LEVEL="patch";;
            minor* | feature* | feat*)
              LEVEL="minor";;
            major* | release*)
              LEVEL="major";;
            *)
              LEVEL="unknown";;
          esac
          echo "Determined level: $LEVEL"
          echo "$LEVEL" >> $GITHUB_OUTPUT

      - name: Get latest tag
        id: latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Bump release version
        id: bump_version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.latest_tag.outputs.tag }}
          level: ${{ steps.determine-prefix.outputs.level }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            This is the release created automatically but always minor.
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          token: ${{ secrets.PAT }}